name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: [ 22.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        run: corepack enable

      - name: Set up Node.js with ${{ matrix.node }} version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - name: Check the format of the code
        run: pnpm lint

      - name: Run the unit tests
        run: pnpm test

      - name: Build the project
        run: pnpm build
